
var YaneuraOu_K_P = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(YaneuraOu_K_P) {
  YaneuraOu_K_P = YaneuraOu_K_P || {};


function d(){g.buffer!=q&&u(g.buffer);return aa}function v(){g.buffer!=q&&u(g.buffer);return ba}function x(){g.buffer!=q&&u(g.buffer);return ca}function da(){g.buffer!=q&&u(g.buffer);return ea}function fa(){g.buffer!=q&&u(g.buffer);return ha}"use strict";var z;z||(z=typeof YaneuraOu_K_P !== 'undefined' ? YaneuraOu_K_P : {});var ia,ja;z.ready=new Promise(function(a,b){ia=a;ja=b});
(function(){function a(){var h=e.shift();if(!b&&void 0!==h){if("quit"===h)return z.terminate();var l=z.ccall("usi_command","number",["string"],[h]);l&&e.unshift(h);f=l?2*f:1;setTimeout(a,f)}}var b=!1,c=[];z.print=function(h){0===c.length?console.log(h):setTimeout(function(){for(var l=0;l<c.length;l++)c[l](h)})};z.addMessageListener=function(h){c.push(h)};z.removeMessageListener=function(h){h=c.indexOf(h);0<=h&&c.splice(h,1)};z.terminate=function(){b=!0;B.lb()};var e=[],f=1;z.postMessage=function(h){e.push(h)};
z.postRun=function(){z.postMessage=function(h){e.push(h);1===e.length&&a()};a()}})();var ka=Object.assign({},z),la=[],ma="./this.program",na=(a,b)=>{throw b;},oa="object"==typeof window,C="function"==typeof importScripts,F="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,G=z.ENVIRONMENT_IS_PTHREAD||!1,H="";function pa(a){return z.locateFile?z.locateFile(a,H):H+a}var I,qa,ra,fs,sa,ta;
if(F){H=C?require("path").dirname(H)+"/":__dirname+"/";ta=()=>{sa||(fs=require("fs"),sa=require("path"))};I=function(b,c){ta();b=sa.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};ra=b=>{b=I(b,!0);b.buffer||(b=new Uint8Array(b));return b};qa=(b,c,e)=>{ta();b=sa.normalize(b);fs.readFile(b,function(f,h){f?e(f):c(h.buffer)})};1<process.argv.length&&(ma=process.argv[1].replace(/\\/g,"/"));la=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof J))throw b;});process.on("unhandledRejection",
function(b){throw b;});na=(b,c)=>{if(noExitRuntime)throw process.exitCode=b,c;c instanceof J||L("exiting due to exception: "+c);process.exit(b)};z.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(oa||C)C?H=self.location.href:"undefined"!=typeof document&&document.currentScript&&(H=document.currentScript.src),
_scriptDir&&(H=_scriptDir),0!==H.indexOf("blob:")?H=H.substr(0,H.replace(/[?#].*/,"").lastIndexOf("/")+1):H="",F||(I=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},C&&(ra=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),qa=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=
c;e.send(null)});F&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var ua=console.log.bind(console),va=console.warn.bind(console);F&&(ta(),ua=a=>fs.writeSync(1,a+"\n"),va=a=>fs.writeSync(2,a+"\n"));var wa=z.print||ua,L=z.printErr||va;Object.assign(z,ka);ka=null;z.arguments&&(la=z.arguments);z.thisProgram&&(ma=z.thisProgram);z.quit&&(na=z.quit);var xa,ya;z.wasmBinary&&(ya=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!=typeof WebAssembly&&M("no native wasm support detected");
var g,za,Aa=!1,Ba="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function N(a,b){b>>>=0;for(var c=b+NaN,e=b;a[e]&&!(e>=c);)++e;if(16<e-b&&a.buffer&&Ba)return Ba.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,e):a.subarray(b,e));for(c="";b<e;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|h);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|l:(f&7)<<18|h<<12|l<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c}
function Ca(a){return(a>>>=0)?N(v(),a):""}
function Da(a,b,c,e){c>>>=0;if(!(0<e))return 0;var f=c;e=c+e-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var n=a.charCodeAt(++h);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=e)break;b[c++>>>0]=l}else{if(2047>=l){if(c+1>=e)break;b[c++>>>0]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++>>>0]=224|l>>12}else{if(c+3>=e)break;b[c++>>>0]=240|l>>18;b[c++>>>0]=128|l>>12&63}b[c++>>>0]=128|l>>6&63}b[c++>>>0]=128|l&63}}b[c>>>0]=0;return c-f}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!=typeof TextDecoder&&new TextDecoder("utf-16le");function Fa(a){var b=Ea(a)+1,c=O(b);Da(a,d(),c,b);return c}function Ga(a,b){d().set(a,b>>>0)}var q,aa,ba,Ha,ca,ea,ha;G&&(q=z.buffer);
function u(a){q=a;z.HEAP8=aa=new Int8Array(a);z.HEAP16=Ha=new Int16Array(a);z.HEAP32=ca=new Int32Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAPU32=ea=new Uint32Array(a);z.HEAPF32=new Float32Array(a);z.HEAPF64=ha=new Float64Array(a)}var Ia=z.INITIAL_MEMORY||92274688;
if(G)g=z.wasmMemory,q=z.buffer;else if(z.wasmMemory)g=z.wasmMemory;else if(g=new WebAssembly.Memory({initial:Ia/65536,maximum:65536,shared:!0}),!(g.buffer instanceof SharedArrayBuffer))throw L("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),F&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");g&&(q=g.buffer);Ia=q.byteLength;u(q);var Ja,Ka=[],La=[],Ma=[],Na=[];function Oa(){G||(z.noFSInit||P.V.Ba||P.V(),P.gb=!1,Pa(La))}function Qa(){var a=z.preRun.shift();Ka.unshift(a)}var Q=0,Ra=null,Sa=null;function Ta(){Q++;z.monitorRunDependencies&&z.monitorRunDependencies(Q)}function Ua(){Q--;z.monitorRunDependencies&&z.monitorRunDependencies(Q);if(0==Q&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}
function M(a){if(G)postMessage({cmd:"onAbort",arg:a});else if(z.onAbort)z.onAbort(a);a="Aborted("+a+")";L(a);Aa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ja(a);throw a;}function Va(){return R.startsWith("data:application/octet-stream;base64,")}var R;R="yaneuraou.k-p.wasm";Va()||(R=pa(R));function Wa(){var a=R;try{if(a==R&&ya)return new Uint8Array(ya);if(ra)return ra(a);throw"both async and sync fetching of the wasm failed";}catch(b){M(b)}}
function Xa(){return ya||!oa&&!C||"function"!=typeof fetch?Promise.resolve().then(function(){return Wa()}):fetch(R,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+R+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}var S,Ya,Za={};function $a(a){var b=B.G[a];b&&(x()[a>>2>>>0]=0,B.jb(b.worker))}
function ab(a){var b=B.Fb();if(!b)return 6;B.ia.push(b);var c=B.G[a.Ha]={worker:b,Ma:a.Ha};b.X=c;var e={cmd:"run",start_routine:a.Yb,arg:a.$,threadInfoStruct:a.Ha};b.ha=()=>{e.time=performance.now();b.postMessage(e,a.dc)};b.loaded&&(b.ha(),delete b.ha);return 0}
var B={I:[],ia:[],qa:[],V:function(){G?B.Ib():B.Hb()},Hb:function(){for(var a=0;32>a;++a)B.Qa()},Ib:function(){B.receiveObjectTransfer=B.Tb;B.threadInit=B.mb;B.setExitStatus=B.Xb;noExitRuntime=!1},G:{},Xb:function(){},lb:function(){for(var a in B.G){var b=B.G[a];b&&b.worker&&B.jb(b.worker)}for(a=0;a<B.I.length;++a)B.I[a].terminate();B.I=[]},jb:function(a){B.Vb(function(){delete B.G[a.X.Ma];B.I.push(a);B.ia.splice(B.ia.indexOf(a),1);bb(a.X.Ma);a.X=void 0})},Vb:function(a){x()[cb>>>2]=0;try{a()}finally{x()[cb>>>
2]=1}},Tb:function(){},mb:function(){for(var a in B.qa)if(B.qa.hasOwnProperty(a))B.qa[a]()},hb:function(a,b){a.onmessage=c=>{c=c.data;var e=c.cmd;a.X&&(B.Ab=a.X.Ma);if(c.targetThread&&c.targetThread!=db()){var f=B.G[c.zc];f?f.worker.postMessage(c,c.transferList):L('Internal error! Worker sent a message "'+e+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processProxyingQueue"===e)eb(c.queue);else if("spawnThread"===e)ab(c);else if("cleanupThread"===e)$a(c.thread);
else if("killThread"===e)c=c.thread,x()[c>>2>>>0]=0,e=B.G[c],delete B.G[c],e.worker.terminate(),bb(c),B.ia.splice(B.ia.indexOf(e.worker),1),e.worker.X=void 0;else if("cancelThread"===e)B.G[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===e)a.loaded=!0,b&&b(a),a.ha&&(a.ha(),delete a.ha);else if("print"===e)wa("Thread "+c.threadId+": "+c.text);else if("printErr"===e)L("Thread "+c.threadId+": "+c.text);else if("alert"===e)alert("Thread "+c.threadId+": "+c.text);else if("setimmediate"===
c.target)a.postMessage(c);else if("onAbort"===e){if(z.onAbort)z.onAbort(c.arg)}else e&&L("worker sent an unknown command "+e);B.Ab=void 0};a.onerror=c=>{L("worker sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};F&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:z.mainScriptUrlOrBlob||_scriptDir,wasmMemory:g,wasmModule:za})},Qa:function(){var a=pa("yaneuraou.k-p.worker.js");
B.I.push(new Worker(a))},Fb:function(){0==B.I.length&&(B.Qa(),B.hb(B.I[0]));return B.I.pop()}};z.PThread=B;function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(z);else{var c=b.nc;"number"==typeof c?void 0===b.$?fb(c)():fb(c)(b.$):c(void 0===b.$?null:b.$)}}}function gb(a){var b=hb();a=a();ib(b);return a}z.establishStackSpace=function(){var a=db(),b=x()[a+44>>2>>>0];a=x()[a+48>>2>>>0];jb(b,b-a);ib(b)};
function kb(a){if(G)return T(1,0,a);try{lb(a)}catch(b){b instanceof J||"unwind"==b||na(1,b)}}var mb=[];function fb(a){var b=mb[a];b||(a>=mb.length&&(mb.length=a+1),mb[a]=b=Ja.get(a));return b}z.invokeEntryPoint=function(a,b){return fb(a)(b)};function nb(a,b,c,e){return G?T(2,1,a,b,c,e):ob(a,b,c,e)}
function ob(a,b,c,e){if("undefined"==typeof SharedArrayBuffer)return L("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(G&&0===f.length)return nb(a,b,c,e);a={Yb:c,Ha:a,$:e,dc:f};return G?(a.hc="spawnThread",postMessage(a,f),0):ab(a)}
var pb=(a,b)=>{for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},U=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=pb(a.split("/").filter(e=>!!e),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},qb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},V=a=>{if("/"===
a)return"/";a=U(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},rb=(a,b)=>U(a+"/"+b);function sb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(F)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){M("randomDevice")}}
function W(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:P.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=pb(a.split("/").filter(e=>!!e),!b).join("/");return(b?"/":"")+a||"."}
var tb=(a,b)=>{function c(l){for(var n=0;n<l.length&&""===l[n];n++);for(var r=l.length-1;0<=r&&""===l[r];r--);return n>r?[]:l.slice(n,r-n+1)}a=W(a).substr(1);b=W(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,h=0;h<e;h++)if(a[h]!==b[h]){f=h;break}e=[];for(h=f;h<a.length;h++)e.push("..");e=e.concat(b.slice(f));return e.join("/")},ub=[];function vb(a,b){ub[a]={input:[],output:[],W:b};P.La(a,wb)}
var wb={open:function(a){var b=ub[a.node.rdev];if(!b)throw new P.g(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.W.flush(a.tty)},flush:function(a){a.tty.W.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.W.bb)throw new P.g(60);for(var f=0,h=0;h<e;h++){try{var l=a.tty.W.bb(a.tty)}catch(n){throw new P.g(29);}if(void 0===l&&0===f)throw new P.g(6);if(null===l||void 0===l)break;f++;b[c+h]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.tty||!a.tty.W.Ia)throw new P.g(60);
try{for(var f=0;f<e;f++)a.tty.W.Ia(a.tty,b[c+f])}catch(h){throw new P.g(29);}e&&(a.node.timestamp=Date.now());return f}},yb={bb:function(a){if(!a.input.length){var b=null;if(F){var c=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(f){if(f.toString().includes("EOF"))e=0;else throw f;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=xb(b,!0)}return a.input.shift()},Ia:function(a,b){null===b||10===b?(wa(N(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(wa(N(a.output,0)),a.output=[])}},zb={Ia:function(a,b){null===b||10===b?(L(N(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(L(N(a.output,0)),a.output=[])}},X={F:null,o:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,
b,c,e){if(P.Jb(c)||P.isFIFO(c))throw new P.g(63);X.F||(X.F={dir:{node:{B:X.h.B,u:X.h.u,lookup:X.h.lookup,K:X.h.K,rename:X.h.rename,unlink:X.h.unlink,rmdir:X.h.rmdir,readdir:X.h.readdir,symlink:X.h.symlink},stream:{C:X.j.C}},file:{node:{B:X.h.B,u:X.h.u},stream:{C:X.j.C,read:X.j.read,write:X.j.write,Z:X.j.Z,da:X.j.da,ga:X.j.ga}},link:{node:{B:X.h.B,u:X.h.u,readlink:X.h.readlink},stream:{}},Sa:{node:{B:X.h.B,u:X.h.u},stream:P.tb}});c=P.createNode(a,b,c,e);P.s(c.mode)?(c.h=X.F.dir.node,c.j=X.F.dir.stream,
c.i={}):P.isFile(c.mode)?(c.h=X.F.file.node,c.j=X.F.file.stream,c.m=0,c.i=null):P.ba(c.mode)?(c.h=X.F.link.node,c.j=X.F.link.stream):P.ka(c.mode)&&(c.h=X.F.Sa.node,c.j=X.F.Sa.stream);c.timestamp=Date.now();a&&(a.i[b]=c,a.timestamp=c.timestamp);return c},pc:function(a){return a.i?a.i.subarray?a.i.subarray(0,a.m):new Uint8Array(a.i):new Uint8Array(0)},Ya:function(a,b){b>>>=0;var c=a.i?a.i.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.i,a.i=new Uint8Array(b),0<
a.m&&a.i.set(c.subarray(0,a.m),0))},Ub:function(a,b){b>>>=0;if(a.m!=b)if(0==b)a.i=null,a.m=0;else{var c=a.i;a.i=new Uint8Array(b);c&&a.i.set(c.subarray(0,Math.min(b,a.m)));a.m=b}},h:{B:function(a){var b={};b.dev=P.ka(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P.s(a.mode)?b.size=4096:P.isFile(a.mode)?b.size=a.m:P.ba(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.rb=4096;b.blocks=
Math.ceil(b.size/b.rb);return b},u:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.Ub(a,b.size)},lookup:function(){throw P.xa[44];},K:function(a,b,c,e){return X.createNode(a,b,c,e)},rename:function(a,b,c){if(P.s(a.mode)){try{var e=P.J(b,c)}catch(h){}if(e)for(var f in e.i)throw new P.g(55);}delete a.parent.i[a.name];a.parent.timestamp=Date.now();a.name=c;b.i[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.i[b];
a.timestamp=Date.now()},rmdir:function(a,b){var c=P.J(a,b),e;for(e in c.i)throw new P.g(55);delete a.i[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.i)a.i.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!P.ba(a.mode))throw new P.g(28);return a.link}},j:{read:function(a,b,c,e,f){var h=a.node.i;if(f>=a.node.m)return 0;a=Math.min(a.node.m-f,e);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),
c);else for(e=0;e<a;e++)b[c+e]=h[f+e];return a},write:function(a,b,c,e,f,h){b.buffer===d().buffer&&(h=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.i||a.i.subarray)){if(h)return a.i=b.subarray(c,c+e),a.m=e;if(0===a.m&&0===f)return a.i=b.slice(c,c+e),a.m=e;if(f+e<=a.m)return a.i.set(b.subarray(c,c+e),f),e}X.Ya(a,f+e);if(a.i.subarray&&b.subarray)a.i.set(b.subarray(c,c+e),f);else for(h=0;h<e;h++)a.i[f+h]=b[c+h];a.m=Math.max(a.m,f+e);return e},C:function(a,b,c){1===c?b+=a.position:
2===c&&P.isFile(a.node.mode)&&(b+=a.node.m);if(0>b)throw new P.g(28);return b},Z:function(a,b,c){X.Ya(a.node,b+c);a.node.m=Math.max(a.node.m,b+c)},da:function(a,b,c,e,f,h){if(0!==b)throw new P.g(28);if(!P.isFile(a.node.mode))throw new P.g(43);a=a.node.i;if(h&2||a.buffer!==q){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;h=65536*Math.ceil(c/65536);(c=Ab(65536,h))?v().fill(0,c,c+h):c=0;if(!c)throw new P.g(48);c>>>=0;d().set(a,c>>>0)}else e=!1,c=a.byteOffset;
return{wc:c,fc:e}},ga:function(a,b,c,e,f){if(!P.isFile(a.node.mode))throw new P.g(43);if(f&2)return 0;X.j.write(a,b,0,e,c,!1);return 0}}};function Bb(a,b,c){var e="al "+a;qa(a,function(f){f||M('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));e&&Ua()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Ta()}
var P={root:null,fa:[],Wa:{},streams:[],Ob:1,D:null,Va:"/",Ba:!1,gb:!0,g:null,xa:{},Cb:null,pa:0,l:(a,b={})=>{a=W(P.cwd(),a);if(!a)return{path:"",node:null};b=Object.assign({wa:!0,Ka:0},b);if(8<b.Ka)throw new P.g(32);a=pb(a.split("/").filter(l=>!!l),!1);for(var c=P.root,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;c=P.J(c,a[f]);e=U(e+"/"+a[f]);P.N(c)&&(!h||h&&b.wa)&&(c=c.ea.root);if(!h||b.A)for(h=0;P.ba(c.mode);)if(c=P.readlink(e),e=W(qb(e),c),c=P.l(e,{Ka:b.Ka+1}).node,40<h++)throw new P.g(32);
}return{path:e,node:c}},M:a=>{for(var b;;){if(P.la(a))return a=a.o.ib,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Aa:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%P.D.length},eb:a=>{var b=P.Aa(a.parent.id,a.name);a.P=P.D[b];P.D[b]=a},fb:a=>{var b=P.Aa(a.parent.id,a.name);if(P.D[b]===a)P.D[b]=a.P;else for(b=P.D[b];b;){if(b.P===a){b.P=a.P;break}b=b.P}},J:(a,b)=>{var c=P.Lb(a);if(c)throw new P.g(c,a);for(c=P.D[P.Aa(a.id,b)];c;c=c.P){var e=
c.name;if(c.parent.id===a.id&&e===b)return c}return P.lookup(a,b)},createNode:(a,b,c,e)=>{a=new P.nb(a,b,c,e);P.eb(a);return a},va:a=>{P.fb(a)},la:a=>a===a.parent,N:a=>!!a.ea,isFile:a=>32768===(a&61440),s:a=>16384===(a&61440),ba:a=>40960===(a&61440),ka:a=>8192===(a&61440),Jb:a=>24576===(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),Db:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Nb:a=>{var b=P.Db[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},Za:a=>
{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},R:(a,b)=>{if(P.gb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Lb:a=>{var b=P.R(a,"x");return b?b:a.h.lookup?0:2},Ga:(a,b)=>{try{return P.J(a,b),20}catch(c){}return P.R(a,"wx")},ma:(a,b,c)=>{try{var e=P.J(a,b)}catch(f){return f.v}if(a=P.R(a,"wx"))return a;if(c){if(!P.s(e.mode))return 54;if(P.la(e)||P.M(e)===P.cwd())return 10}else if(P.s(e.mode))return 31;
return 0},Mb:(a,b)=>a?P.ba(a.mode)?32:P.s(a.mode)&&("r"!==P.Za(b)||b&512)?31:P.R(a,P.Za(b)):44,ob:4096,Pb:(a=0,b=P.ob)=>{for(;a<=b;a++)if(!P.streams[a])return a;throw new P.g(33);},U:a=>P.streams[a],Ua:(a,b,c)=>{P.ta||(P.ta=function(){this.oa={}},P.ta.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}},flags:{get:function(){return this.oa.flags},set:function(e){this.oa.flags=e}},position:{get oc(){return this.oa.position},set:function(e){this.oa.position=e}}});a=Object.assign(new P.ta,
a);b=P.Pb(b,c);a.fd=b;return P.streams[b]=a},ub:a=>{P.streams[a]=null},tb:{open:a=>{a.j=P.Eb(a.node.rdev).j;a.j.open&&a.j.open(a)},C:()=>{throw new P.g(70);}},Fa:a=>a>>8,sc:a=>a&255,O:(a,b)=>a<<8|b,La:(a,b)=>{P.Wa[a]={j:b}},Eb:a=>P.Wa[a],ab:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.fa)}return b},kb:(a,b)=>{function c(l){P.pa--;return b(l)}function e(l){if(l){if(!e.Bb)return e.Bb=!0,c(l)}else++h>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);P.pa++;1<P.pa&&L("warning: "+
P.pa+" FS.syncfs operations in flight at once, probably just doing extra work");var f=P.ab(P.root.o),h=0;f.forEach(l=>{if(!l.type.kb)return e(null);l.type.kb(l,a,e)})},o:(a,b,c)=>{var e="/"===c,f=!c;if(e&&P.root)throw new P.g(10);if(!e&&!f){var h=P.l(c,{wa:!1});c=h.path;h=h.node;if(P.N(h))throw new P.g(10);if(!P.s(h.mode))throw new P.g(54);}b={type:a,vc:b,ib:c,fa:[]};a=a.o(b);a.o=b;b.root=a;e?P.root=a:h&&(h.ea=b,h.o&&h.o.fa.push(b));return a},Bc:a=>{a=P.l(a,{wa:!1});if(!P.N(a.node))throw new P.g(28);
a=a.node;var b=a.ea,c=P.ab(b);Object.keys(P.D).forEach(e=>{for(e=P.D[e];e;){var f=e.P;c.includes(e.o)&&P.va(e);e=f}});a.ea=null;a.o.fa.splice(a.o.fa.indexOf(b),1)},lookup:(a,b)=>a.h.lookup(a,b),K:(a,b,c)=>{var e=P.l(a,{parent:!0}).node;a=V(a);if(!a||"."===a||".."===a)throw new P.g(28);var f=P.Ga(e,a);if(f)throw new P.g(f);if(!e.h.K)throw new P.g(63);return e.h.K(e,a,b,c)},create:(a,b)=>P.K(a,(void 0!==b?b:438)&4095|32768,0),mkdir:(a,b)=>P.K(a,(void 0!==b?b:511)&1023|16384,0),tc:(a,b)=>{a=a.split("/");
for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{P.mkdir(c,b)}catch(f){if(20!=f.v)throw f;}}},na:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return P.K(a,b|8192,c)},symlink:(a,b)=>{if(!W(a))throw new P.g(44);var c=P.l(b,{parent:!0}).node;if(!c)throw new P.g(44);b=V(b);var e=P.Ga(c,b);if(e)throw new P.g(e);if(!c.h.symlink)throw new P.g(63);return c.h.symlink(c,b,a)},rename:(a,b)=>{var c=qb(a),e=qb(b),f=V(a),h=V(b);var l=P.l(a,{parent:!0});var n=l.node;l=P.l(b,{parent:!0});l=l.node;if(!n||
!l)throw new P.g(44);if(n.o!==l.o)throw new P.g(75);var r=P.J(n,f);a=tb(a,e);if("."!==a.charAt(0))throw new P.g(28);a=tb(b,c);if("."!==a.charAt(0))throw new P.g(55);try{var m=P.J(l,h)}catch(p){}if(r!==m){b=P.s(r.mode);if(f=P.ma(n,f,b))throw new P.g(f);if(f=m?P.ma(l,h,b):P.Ga(l,h))throw new P.g(f);if(!n.h.rename)throw new P.g(63);if(P.N(r)||m&&P.N(m))throw new P.g(10);if(l!==n&&(f=P.R(n,"w")))throw new P.g(f);P.fb(r);try{n.h.rename(r,l,h)}catch(p){throw p;}finally{P.eb(r)}}},rmdir:a=>{var b=P.l(a,
{parent:!0}).node;a=V(a);var c=P.J(b,a),e=P.ma(b,a,!0);if(e)throw new P.g(e);if(!b.h.rmdir)throw new P.g(63);if(P.N(c))throw new P.g(10);b.h.rmdir(b,a);P.va(c)},readdir:a=>{a=P.l(a,{A:!0}).node;if(!a.h.readdir)throw new P.g(54);return a.h.readdir(a)},unlink:a=>{var b=P.l(a,{parent:!0}).node;if(!b)throw new P.g(44);a=V(a);var c=P.J(b,a),e=P.ma(b,a,!1);if(e)throw new P.g(e);if(!b.h.unlink)throw new P.g(63);if(P.N(c))throw new P.g(10);b.h.unlink(b,a);P.va(c)},readlink:a=>{a=P.l(a).node;if(!a)throw new P.g(44);
if(!a.h.readlink)throw new P.g(28);return W(P.M(a.parent),a.h.readlink(a))},stat:(a,b)=>{a=P.l(a,{A:!b}).node;if(!a)throw new P.g(44);if(!a.h.B)throw new P.g(63);return a.h.B(a)},lstat:a=>P.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?P.l(a,{A:!c}).node:a;if(!a.h.u)throw new P.g(63);a.h.u(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{P.chmod(a,b,!0)},fchmod:(a,b)=>{a=P.U(a);if(!a)throw new P.g(8);P.chmod(a.node,b)},chown:(a,b,c,e)=>{a="string"==typeof a?P.l(a,{A:!e}).node:
a;if(!a.h.u)throw new P.g(63);a.h.u(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{P.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=P.U(a);if(!a)throw new P.g(8);P.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new P.g(28);a="string"==typeof a?P.l(a,{A:!0}).node:a;if(!a.h.u)throw new P.g(63);if(P.s(a.mode))throw new P.g(31);if(!P.isFile(a.mode))throw new P.g(28);var c=P.R(a,"w");if(c)throw new P.g(c);a.h.u(a,{size:b,timestamp:Date.now()})},mc:(a,b)=>{a=P.U(a);if(!a)throw new P.g(8);if(0===(a.flags&2097155))throw new P.g(28);
P.truncate(a.node,b)},Cc:(a,b,c)=>{a=P.l(a,{A:!0}).node;a.h.u(a,{timestamp:Math.max(b,c)})},open:(a,b,c)=>{if(""===a)throw new P.g(44);b="string"==typeof b?P.Nb(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=U(a);try{e=P.l(a,{A:!(b&131072)}).node}catch(h){}}var f=!1;if(b&64)if(e){if(b&128)throw new P.g(20);}else e=P.K(a,c,0),f=!0;if(!e)throw new P.g(44);P.ka(e.mode)&&(b&=-513);if(b&65536&&!P.s(e.mode))throw new P.g(54);if(!f&&(c=P.Mb(e,b)))throw new P.g(c);
b&512&&!f&&P.truncate(e,0);b&=-131713;e=P.Ua({node:e,path:P.M(e),flags:b,seekable:!0,position:0,j:e.j,ec:[],error:!1});e.j.open&&e.j.open(e);!z.logReadFiles||b&1||(P.Ja||(P.Ja={}),a in P.Ja||(P.Ja[a]=1));return e},close:a=>{if(P.aa(a))throw new P.g(8);a.za&&(a.za=null);try{a.j.close&&a.j.close(a)}catch(b){throw b;}finally{P.ub(a.fd)}a.fd=null},aa:a=>null===a.fd,C:(a,b,c)=>{if(P.aa(a))throw new P.g(8);if(!a.seekable||!a.j.C)throw new P.g(70);if(0!=c&&1!=c&&2!=c)throw new P.g(28);a.position=a.j.C(a,
b,c);a.ec=[];return a.position},read:(a,b,c,e,f)=>{c>>>=0;if(0>e||0>f)throw new P.g(28);if(P.aa(a))throw new P.g(8);if(1===(a.flags&2097155))throw new P.g(8);if(P.s(a.node.mode))throw new P.g(31);if(!a.j.read)throw new P.g(28);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new P.g(70);b=a.j.read(a,b,c,e,f);h||(a.position+=b);return b},write:(a,b,c,e,f,h)=>{c>>>=0;if(0>e||0>f)throw new P.g(28);if(P.aa(a))throw new P.g(8);if(0===(a.flags&2097155))throw new P.g(8);if(P.s(a.node.mode))throw new P.g(31);
if(!a.j.write)throw new P.g(28);a.seekable&&a.flags&1024&&P.C(a,0,2);var l="undefined"!=typeof f;if(!l)f=a.position;else if(!a.seekable)throw new P.g(70);b=a.j.write(a,b,c,e,f,h);l||(a.position+=b);return b},Z:(a,b,c)=>{if(P.aa(a))throw new P.g(8);if(0>b||0>=c)throw new P.g(28);if(0===(a.flags&2097155))throw new P.g(8);if(!P.isFile(a.node.mode)&&!P.s(a.node.mode))throw new P.g(43);if(!a.j.Z)throw new P.g(138);a.j.Z(a,b,c)},da:(a,b,c,e,f,h)=>{b>>>=0;if(0!==(f&2)&&0===(h&2)&&2!==(a.flags&2097155))throw new P.g(2);
if(1===(a.flags&2097155))throw new P.g(2);if(!a.j.da)throw new P.g(43);return a.j.da(a,b,c,e,f,h)},ga:(a,b,c,e,f)=>a&&a.j.ga?a.j.ga(a,b,c>>>0,e,f):0,uc:()=>0,Ca:(a,b,c)=>{if(!a.j.Ca)throw new P.g(59);return a.j.Ca(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=P.open(a,b.flags);a=P.stat(a).size;var f=new Uint8Array(a);P.read(e,f,0,a,0);"utf8"===b.encoding?c=N(f,
0):"binary"===b.encoding&&(c=f);P.close(e);return c},writeFile:(a,b,c={})=>{c.flags=c.flags||577;a=P.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(Ea(b)+1);b=Da(b,e,0,e.length);P.write(a,e,0,b,void 0,c.sb)}else if(ArrayBuffer.isView(b))P.write(a,b,0,b.byteLength,void 0,c.sb);else throw Error("Unsupported data type");P.close(a)},cwd:()=>P.Va,chdir:a=>{a=P.l(a,{A:!0});if(null===a.node)throw new P.g(44);if(!P.s(a.node.mode))throw new P.g(54);var b=P.R(a.node,"x");if(b)throw new P.g(b);
P.Va=a.path},wb:()=>{P.mkdir("/tmp");P.mkdir("/home");P.mkdir("/home/web_user")},vb:()=>{P.mkdir("/dev");P.La(P.O(1,3),{read:()=>0,write:(b,c,e,f)=>f});P.na("/dev/null",P.O(1,3));vb(P.O(5,0),yb);vb(P.O(6,0),zb);P.na("/dev/tty",P.O(5,0));P.na("/dev/tty1",P.O(6,0));var a=sb();P.L("/dev","random",a);P.L("/dev","urandom",a);P.mkdir("/dev/shm");P.mkdir("/dev/shm/tmp")},yb:()=>{P.mkdir("/proc");var a=P.mkdir("/proc/self");P.mkdir("/proc/self/fd");P.o({o:()=>{var b=P.createNode(a,"fd",16895,73);b.h={lookup:(c,
e)=>{var f=P.U(+e);if(!f)throw new P.g(8);c={parent:null,o:{ib:"fake"},h:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},zb:()=>{z.stdin?P.L("/dev","stdin",z.stdin):P.symlink("/dev/tty","/dev/stdin");z.stdout?P.L("/dev","stdout",null,z.stdout):P.symlink("/dev/tty","/dev/stdout");z.stderr?P.L("/dev","stderr",null,z.stderr):P.symlink("/dev/tty1","/dev/stderr");P.open("/dev/stdin",0);P.open("/dev/stdout",1);P.open("/dev/stderr",1)},Xa:()=>{P.g||(P.g=function(a,b){this.node=
b;this.Wb=function(c){this.v=c};this.Wb(a);this.message="FS error"},P.g.prototype=Error(),P.g.prototype.constructor=P.g,[44].forEach(a=>{P.xa[a]=new P.g(a);P.xa[a].stack="<generic error, no stack>"}))},Zb:()=>{P.Xa();P.D=Array(4096);P.o(X,{},"/");P.wb();P.vb();P.yb();P.Cb={MEMFS:X}},V:(a,b,c)=>{P.V.Ba=!0;P.Xa();z.stdin=a||z.stdin;z.stdout=b||z.stdout;z.stderr=c||z.stderr;P.zb()},xc:()=>{P.V.Ba=!1;for(var a=0;a<P.streams.length;a++){var b=P.streams[a];b&&P.close(b)}},ya:(a,b)=>{var c=0;a&&(c|=365);
b&&(c|=146);return c},lc:(a,b)=>{a=P.ua(a,b);return a.exists?a.object:null},ua:(a,b)=>{try{var c=P.l(a,{A:!b});a=c.path}catch(f){}var e={la:!1,exists:!1,error:0,name:null,path:null,object:null,Qb:!1,Sb:null,Rb:null};try{c=P.l(a,{parent:!0}),e.Qb=!0,e.Sb=c.path,e.Rb=c.node,e.name=V(a),c=P.l(a,{A:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.la="/"===c.path}catch(f){e.error=f.v}return e},jc:(a,b)=>{a="string"==typeof a?a:P.M(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();
if(c){var e=U(a+"/"+c);try{P.mkdir(e)}catch(f){}a=e}}return e},xb:(a,b,c,e,f)=>{a="string"==typeof a?a:P.M(a);b=U(a+"/"+b);return P.create(b,P.ya(e,f))},Ta:(a,b,c,e,f,h)=>{var l=b;a&&(a="string"==typeof a?a:P.M(a),l=b?U(a+"/"+b):a);a=P.ya(e,f);l=P.create(l,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(f=c.length;e<f;++e)b[e]=c.charCodeAt(e);c=b}P.chmod(l,a|146);b=P.open(l,577);P.write(b,c,0,c.length,0,h);P.close(b);P.chmod(l,a)}return l},L:(a,b,c,e)=>{a=rb("string"==typeof a?a:P.M(a),
b);b=P.ya(!!c,!!e);P.L.Fa||(P.L.Fa=64);var f=P.O(P.L.Fa++,0);P.La(f,{open:h=>{h.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(h,l,n,r)=>{for(var m=0,p=0;p<r;p++){try{var y=c()}catch(A){throw new P.g(29);}if(void 0===y&&0===m)throw new P.g(6);if(null===y||void 0===y)break;m++;l[n+p]=y}m&&(h.node.timestamp=Date.now());return m},write:(h,l,n,r)=>{for(var m=0;m<r;m++)try{e(l[n+m])}catch(p){throw new P.g(29);}r&&(h.node.timestamp=Date.now());return m}});return P.na(a,b,f)},$a:a=>{if(a.Da||
a.Kb||a.link||a.i)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(I)try{a.i=xb(I(a.url),!0),a.m=a.i.length}catch(b){throw new P.g(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},ic:(a,b,c,e,f)=>{function h(){this.Ea=!1;this.ja=[]}h.prototype.get=function(m){if(!(m>this.length-
1||0>m)){var p=m%this.chunkSize;return this.cb(m/this.chunkSize|0)[p]}};h.prototype.Gb=function(m){this.cb=m};h.prototype.Ra=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var p=Number(m.getResponseHeader("Content-length")),y,A=(y=m.getResponseHeader("Accept-Ranges"))&&"bytes"===y;m=(y=m.getResponseHeader("Content-Encoding"))&&"gzip"===y;var k=1048576;A||(k=p);var t=this;t.Gb(w=>
{var D=w*k,K=(w+1)*k-1;K=Math.min(K,p-1);if("undefined"==typeof t.ja[w]){var ec=t.ja;if(D>K)throw Error("invalid range ("+D+", "+K+") or no bytes requested!");if(K>p-1)throw Error("only "+p+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",c,!1);p!==k&&E.setRequestHeader("Range","bytes="+D+"-"+K);E.responseType="arraybuffer";E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);if(!(200<=E.status&&300>E.status||304===E.status))throw Error("Couldn't load "+
c+". Status: "+E.status);D=void 0!==E.response?new Uint8Array(E.response||[]):xb(E.responseText||"",!0);ec[w]=D}if("undefined"==typeof t.ja[w])throw Error("doXHR failed!");return t.ja[w]});if(m||!p)k=p=1,k=p=this.cb(0).length,wa("LazyFiles on gzip forces download of the whole file when length is accessed");this.qb=p;this.pb=k;this.Ea=!0};if("undefined"!=typeof XMLHttpRequest){if(!C)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new h;Object.defineProperties(l,{length:{get:function(){this.Ea||this.Ra();return this.qb}},chunkSize:{get:function(){this.Ea||this.Ra();return this.pb}}});l={Da:!1,i:l}}else l={Da:!1,url:c};var n=P.xb(a,b,l,e,f);l.i?n.i=l.i:l.url&&(n.i=null,n.url=l.url);Object.defineProperties(n,{m:{get:function(){return this.i.length}}});var r={};Object.keys(n.j).forEach(m=>{var p=n.j[m];r[m]=function(){P.$a(n);return p.apply(null,arguments)}});r.read=(m,p,y,A,k)=>{P.$a(n);m=m.node.i;if(k>=m.length)return 0;
A=Math.min(m.length-k,A);if(m.slice)for(var t=0;t<A;t++)p[y+t]=m[k+t];else for(t=0;t<A;t++)p[y+t]=m.get(k+t);return A};n.j=r;return n},kc:(a,b,c,e,f,h,l,n,r,m)=>{function p(A){function k(t){m&&m();n||P.Ta(a,b,t,e,f,r);h&&h();Ua()}Cb.qc(A,y,k,()=>{l&&l();Ua()})||k(A)}var y=b?W(U(a+"/"+b)):a;Ta();"string"==typeof c?Bb(c,A=>p(A),l):p(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Oa:()=>"EM_FS_"+window.location.pathname,Pa:20,Y:"FILE_DATA",yc:(a,b,
c)=>{b=b||(()=>{});c=c||(()=>{});var e=P.indexedDB();try{var f=e.open(P.Oa(),P.Pa)}catch(h){return c(h)}f.onupgradeneeded=()=>{wa("creating db");f.result.createObjectStore(P.Y)};f.onsuccess=()=>{var h=f.result.transaction([P.Y],"readwrite"),l=h.objectStore(P.Y),n=0,r=0,m=a.length;a.forEach(p=>{p=l.put(P.ua(p).object.i,p);p.onsuccess=()=>{n++;n+r==m&&(0==r?b():c())};p.onerror=()=>{r++;n+r==m&&(0==r?b():c())}});h.onerror=c};f.onerror=c},rc:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=P.indexedDB();try{var f=
e.open(P.Oa(),P.Pa)}catch(h){return c(h)}f.onupgradeneeded=c;f.onsuccess=()=>{var h=f.result;try{var l=h.transaction([P.Y],"readonly")}catch(y){c(y);return}var n=l.objectStore(P.Y),r=0,m=0,p=a.length;a.forEach(y=>{var A=n.get(y);A.onsuccess=()=>{P.ua(y).exists&&P.unlink(y);P.Ta(qb(y),V(y),A.result,!0,!0,!0);r++;r+m==p&&(0==m?b():c())};A.onerror=()=>{m++;r+m==p&&(0==m?b():c())}});l.onerror=c};f.onerror=c}},Db=void 0;function Y(){Db+=4;return x()[Db-4>>2>>>0]}
function Z(a){a=P.U(a);if(!a)throw new P.g(8);return a}function Eb(a,b,c){if(G)return T(3,1,a,b,c);Db=c;try{var e=Z(a);switch(b){case 0:var f=Y();return 0>f?-28:P.Ua(e,f).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=Y(),e.flags|=f,0;case 5:return f=Y(),g.buffer!=q&&u(g.buffer),Ha[f+0>>1>>>0]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return x()[Fb()>>2>>>0]=28,-1;default:return-28}}catch(h){if("undefined"==typeof P||!(h instanceof P.g))throw h;return-h.v}}
function Gb(a,b){if(G)return T(4,1,a,b);try{if(0===b)return-28;var c=P.cwd(),e=Ea(c)+1;if(b<e)return-68;Da(c,v(),a,b);return e}catch(f){if("undefined"==typeof P||!(f instanceof P.g))throw f;return-f.v}}
function Hb(a,b,c){if(G)return T(5,1,a,b,c);Db=c;try{var e=Z(a);switch(b){case 21509:case 21505:return e.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var f=Y();return x()[f>>2>>>0]=0;case 21520:return e.tty?-28:-59;case 21531:return f=Y(),P.Ca(e,b,f);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:M("bad ioctl syscall "+b)}}catch(h){if("undefined"==typeof P||!(h instanceof P.g))throw h;return-h.v}}
function Ib(a,b,c,e){if(G)return T(6,1,a,b,c,e);Db=e;try{b=Ca(b);var f=b;if("/"===f.charAt(0))b=f;else{if(-100===a)var h=P.cwd();else{var l=P.U(a);if(!l)throw new P.g(8);h=l.path}if(0==f.length)throw new P.g(44);b=U(h+"/"+f)}var n=e?Y():0;return P.open(b,c,n).fd}catch(r){if("undefined"==typeof P||!(r instanceof P.g))throw r;return-r.v}}function eb(a){Atomics.store(x(),a>>2,1);db()&&Jb(a);Atomics.compareExchange(x(),a>>2,1,0)}z.executeNotifiedProxyingQueue=eb;var Kb;
Kb=F?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:G?()=>performance.now()-z.__performance_now_clock_drift:()=>performance.now();function T(a,b){var c=arguments.length-2,e=arguments;return gb(function(){for(var f=O(8*c),h=f>>3,l=0;l<c;l++){var n=e[2+l];fa()[h+l>>>0]=n}return Lb(a,c,f,b)})}var Mb=[],Nb={};
function Ob(){if(!Pb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ma||"./this.program"},b;for(b in Nb)void 0===Nb[b]?delete a[b]:a[b]=Nb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Pb=c}return Pb}var Pb;
function Qb(a,b){if(G)return T(7,1,a,b);var c=0;Ob().forEach(function(e,f){var h=b+c;f=x()[a+4*f>>2>>>0]=h;for(h=0;h<e.length;++h)d()[f++>>0>>>0]=e.charCodeAt(h);d()[f>>0>>>0]=0;c+=e.length+1});return 0}function Rb(a,b){if(G)return T(8,1,a,b);var c=Ob();x()[a>>2>>>0]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});x()[b>>2>>>0]=e;return 0}function Sb(a){if(G)return T(9,1,a);try{var b=Z(a);P.close(b);return 0}catch(c){if("undefined"==typeof P||!(c instanceof P.g))throw c;return c.v}}
function Tb(a,b,c,e){if(G)return T(10,1,a,b,c,e);try{a:{var f=Z(a);a=b;for(var h=b=0;h<c;h++){var l=da()[a>>2>>>0],n=da()[a+4>>2>>>0];a+=8;var r=P.read(f,d(),l,n,void 0);if(0>r){var m=-1;break a}b+=r;if(r<n)break}m=b}x()[e>>2>>>0]=m;return 0}catch(p){if("undefined"==typeof P||!(p instanceof P.g))throw p;return p.v}}
function Ub(a,b,c,e,f){if(G)return T(11,1,a,b,c,e,f);try{var h=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return 61;P.C(h,a,e);Ya=[h.position>>>0,(S=h.position,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];x()[f>>2>>>0]=Ya[0];x()[f+4>>2>>>0]=Ya[1];h.za&&0===a&&0===e&&(h.za=null);return 0}catch(l){if("undefined"==typeof P||!(l instanceof P.g))throw l;return l.v}}
function Vb(a,b,c,e){if(G)return T(12,1,a,b,c,e);try{a:{var f=Z(a);a=b;for(var h=b=0;h<c;h++){var l=da()[a>>2>>>0],n=da()[a+4>>2>>>0];a+=8;var r=P.write(f,d(),l,n,void 0);if(0>r){var m=-1;break a}b+=r}m=b}x()[e>>2>>>0]=m;return 0}catch(p){if("undefined"==typeof P||!(p instanceof P.g))throw p;return p.v}}function Wb(a){return 0===a%4&&(0!==a%100||0===a%400)}var Xb=[31,29,31,30,31,30,31,31,30,31,30,31],Yb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Zb(a,b,c,e){function f(k,t,w){for(k="number"==typeof k?k.toString():k||"";k.length<t;)k=w[0]+k;return k}function h(k,t){return f(k,t,"0")}function l(k,t){function w(K){return 0>K?-1:0<K?1:0}var D;0===(D=w(k.getFullYear()-t.getFullYear()))&&0===(D=w(k.getMonth()-t.getMonth()))&&(D=w(k.getDate()-t.getDate()));return D}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function r(k){var t=k.S;for(k=new Date((new Date(k.T+1900,0,1)).getTime());0<t;){var w=k.getMonth(),D=(Wb(k.getFullYear())?Xb:Yb)[w];if(t>D-k.getDate())t-=D-k.getDate()+1,k.setDate(1),11>w?k.setMonth(w+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+t);break}}w=new Date(k.getFullYear()+1,0,4);t=n(new Date(k.getFullYear(),0,
4));w=n(w);return 0>=l(t,k)?0>=l(w,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=x()[e+40>>2>>>0];e={bc:x()[e>>2>>>0],ac:x()[e+4>>2>>>0],ra:x()[e+8>>2>>>0],Na:x()[e+12>>2>>>0],sa:x()[e+16>>2>>>0],T:x()[e+20>>2>>>0],H:x()[e+24>>2>>>0],S:x()[e+28>>2>>>0],Ac:x()[e+32>>2>>>0],$b:x()[e+36>>2>>>0],cc:m?Ca(m):""};c=Ca(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C",
"%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");m={"%a":function(k){return y[k.H].substring(0,3)},"%A":function(k){return y[k.H]},
"%b":function(k){return A[k.sa].substring(0,3)},"%B":function(k){return A[k.sa]},"%C":function(k){return h((k.T+1900)/100|0,2)},"%d":function(k){return h(k.Na,2)},"%e":function(k){return f(k.Na,2," ")},"%g":function(k){return r(k).toString().substring(2)},"%G":function(k){return r(k)},"%H":function(k){return h(k.ra,2)},"%I":function(k){k=k.ra;0==k?k=12:12<k&&(k-=12);return h(k,2)},"%j":function(k){for(var t=0,w=0;w<=k.sa-1;t+=(Wb(k.T+1900)?Xb:Yb)[w++]);return h(k.Na+t,3)},"%m":function(k){return h(k.sa+
1,2)},"%M":function(k){return h(k.ac,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ra&&12>k.ra?"AM":"PM"},"%S":function(k){return h(k.bc,2)},"%t":function(){return"\t"},"%u":function(k){return k.H||7},"%U":function(k){return h(Math.floor((k.S+7-k.H)/7),2)},"%V":function(k){var t=Math.floor((k.S+7-(k.H+6)%7)/7);2>=(k.H+371-k.S-2)%7&&t++;if(t)53==t&&(w=(k.H+371-k.S)%7,4==w||3==w&&Wb(k.T)||(t=1));else{t=52;var w=(k.H+7-k.S-1)%7;(4==w||5==w&&Wb(k.T%400-1))&&t++}return h(t,2)},"%w":function(k){return k.H},
"%W":function(k){return h(Math.floor((k.S+7-(k.H+6)%7)/7),2)},"%y":function(k){return(k.T+1900).toString().substring(2)},"%Y":function(k){return k.T+1900},"%z":function(k){k=k.$b;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.cc},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(p in m)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),m[p](e)));c=c.replace(/\0\0/g,"%");p=xb(c,!1);if(p.length>b)return 0;Ga(p,a);return p.length-
1}B.V();function $b(a,b,c,e){a||(a=this);this.parent=a;this.o=a.o;this.ea=null;this.id=P.Ob++;this.name=b;this.mode=c;this.h={};this.j={};this.rdev=e}Object.defineProperties($b.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Kb:{get:function(){return P.s(this.mode)}},Da:{get:function(){return P.ka(this.mode)}}});P.nb=$b;P.Zb();
var Cb,ac=[null,kb,nb,Eb,Gb,Hb,Ib,Qb,Rb,Sb,Tb,Ub,Vb];function xb(a,b){var c=Array(Ea(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}
var dc={__call_main:function(a,b){noExitRuntime=!0;bc(a,b)},__emscripten_init_main_thread_js:function(a){cc(a,!C,1,!oa);B.mb()},__emscripten_thread_cleanup:function(a){G?postMessage({cmd:"cleanupThread",thread:a}):$a(a)},__pthread_create_js:ob,__syscall_fcntl64:Eb,__syscall_getcwd:Gb,__syscall_ioctl:Hb,__syscall_openat:Ib,_emscripten_date_now:function(){return Date.now()},_emscripten_default_pthread_stack_size:function(){return 2097152},_emscripten_get_now_is_monotonic:function(){return!0},_emscripten_notify_task_queue:function(a,
b,c,e){if(a==b)setTimeout(()=>eb(e));else if(G)postMessage({targetThread:a,cmd:"processProxyingQueue",queue:e});else{a=(a=B.G[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processProxyingQueue",queue:e})}return 1},_emscripten_set_offscreencanvas_size:function(){return-1},abort:function(){M("")},emscripten_check_blocking_allowed:function(){F||C||(xa||(xa={}),xa["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||
(xa["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,L("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},emscripten_get_now:Kb,emscripten_memcpy_big:function(a,b,c){v().copyWithin(a>>>0,b>>>0,b+c>>>0)},emscripten_receive_on_main_thread_js:function(a,b,c){Mb.length=b;c>>=3;for(var e=0;e<b;e++)Mb[e]=fa()[c+e>>>0];return(0>
a?Za[-a-1]:ac[a]).apply(null,Mb)},emscripten_resize_heap:function(a){var b=v().length;a>>>=0;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);f=f.min.call(f,4294901760,e+(65536-e%65536)%65536);a:{try{g.grow(f-q.byteLength+65535>>>16);u(g.buffer);var h=1;break a}catch(l){}h=void 0}if(h)return!0}return!1},emscripten_unwind_to_js_event_loop:function(){throw"unwind";},environ_get:Qb,environ_sizes_get:Rb,exit:function(a){lb(a)},
fd_close:Sb,fd_read:Tb,fd_seek:Ub,fd_write:Vb,memory:g||z.wasmMemory,setTempRet0:function(){},strftime_l:function(a,b,c,e){return Zb(a,b,c,e)}};
(function(){function a(f,h){z.asm=f.exports;B.qa.push(z.asm.emscripten_tls_init);Ja=z.asm.__indirect_function_table;La.unshift(z.asm.__wasm_call_ctors);za=h;if(!G){var l=B.I.length;B.I.forEach(function(n){B.hb(n,function(){--l||Ua()})})}}function b(f){a(f.instance,f.module)}function c(f){return Xa().then(function(h){return WebAssembly.instantiate(h,e)}).then(function(h){return h}).then(f,function(h){L("failed to asynchronously prepare wasm: "+h);M(h)})}var e={env:dc,wasi_snapshot_preview1:dc};G||
Ta();if(z.instantiateWasm)try{return z.instantiateWasm(e,a)}catch(f){return L("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return ya||"function"!=typeof WebAssembly.instantiateStreaming||Va()||"function"!=typeof fetch?c(b):fetch(R,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(h){L("wasm streaming compile failed: "+h);L("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ja);return{}})();
z.___wasm_call_ctors=function(){return(z.___wasm_call_ctors=z.asm.__wasm_call_ctors).apply(null,arguments)};var bc=z._main=function(){return(bc=z._main=z.asm.main).apply(null,arguments)};z._free=function(){return(z._free=z.asm.free).apply(null,arguments)};z._usi_command=function(){return(z._usi_command=z.asm.usi_command).apply(null,arguments)};z._emscripten_tls_init=function(){return(z._emscripten_tls_init=z.asm.emscripten_tls_init).apply(null,arguments)};
var Ab=z._emscripten_builtin_memalign=function(){return(Ab=z._emscripten_builtin_memalign=z.asm.emscripten_builtin_memalign).apply(null,arguments)},Fb=z.___errno_location=function(){return(Fb=z.___errno_location=z.asm.__errno_location).apply(null,arguments)};z._emscripten_proxy_main=function(){return(z._emscripten_proxy_main=z.asm.emscripten_proxy_main).apply(null,arguments)};
var cc=z.__emscripten_thread_init=function(){return(cc=z.__emscripten_thread_init=z.asm._emscripten_thread_init).apply(null,arguments)};z.__emscripten_thread_crashed=function(){return(z.__emscripten_thread_crashed=z.asm._emscripten_thread_crashed).apply(null,arguments)};var db=z._pthread_self=function(){return(db=z._pthread_self=z.asm.pthread_self).apply(null,arguments)};
z._emscripten_main_thread_process_queued_calls=function(){return(z._emscripten_main_thread_process_queued_calls=z.asm.emscripten_main_thread_process_queued_calls).apply(null,arguments)};z._malloc=function(){return(z._malloc=z.asm.malloc).apply(null,arguments)};z._emscripten_main_browser_thread_id=function(){return(z._emscripten_main_browser_thread_id=z.asm.emscripten_main_browser_thread_id).apply(null,arguments)};
var Lb=z._emscripten_run_in_main_runtime_thread_js=function(){return(Lb=z._emscripten_run_in_main_runtime_thread_js=z.asm.emscripten_run_in_main_runtime_thread_js).apply(null,arguments)};z._emscripten_dispatch_to_thread_=function(){return(z._emscripten_dispatch_to_thread_=z.asm.emscripten_dispatch_to_thread_).apply(null,arguments)};
var Jb=z.__emscripten_proxy_execute_task_queue=function(){return(Jb=z.__emscripten_proxy_execute_task_queue=z.asm._emscripten_proxy_execute_task_queue).apply(null,arguments)},bb=z.__emscripten_thread_free_data=function(){return(bb=z.__emscripten_thread_free_data=z.asm._emscripten_thread_free_data).apply(null,arguments)};z.__emscripten_thread_exit=function(){return(z.__emscripten_thread_exit=z.asm._emscripten_thread_exit).apply(null,arguments)};
var jb=z._emscripten_stack_set_limits=function(){return(jb=z._emscripten_stack_set_limits=z.asm.emscripten_stack_set_limits).apply(null,arguments)},hb=z.stackSave=function(){return(hb=z.stackSave=z.asm.stackSave).apply(null,arguments)},ib=z.stackRestore=function(){return(ib=z.stackRestore=z.asm.stackRestore).apply(null,arguments)},O=z.stackAlloc=function(){return(O=z.stackAlloc=z.asm.stackAlloc).apply(null,arguments)};
z.dynCall_jiji=function(){return(z.dynCall_jiji=z.asm.dynCall_jiji).apply(null,arguments)};z.dynCall_viijii=function(){return(z.dynCall_viijii=z.asm.dynCall_viijii).apply(null,arguments)};z.dynCall_iiiiij=function(){return(z.dynCall_iiiiij=z.asm.dynCall_iiiiij).apply(null,arguments)};z.dynCall_iiiiijj=function(){return(z.dynCall_iiiiijj=z.asm.dynCall_iiiiijj).apply(null,arguments)};z.dynCall_iiiiiijj=function(){return(z.dynCall_iiiiiijj=z.asm.dynCall_iiiiiijj).apply(null,arguments)};
var cb=z.__emscripten_allow_main_runtime_queued_calls=923424;z.ccall=function(a,b,c,e){var f={string:function(m){var p=0;if(null!==m&&void 0!==m&&0!==m){var y=(m.length<<2)+1,A=p=O(y);Da(m,v(),A,y)}return p},array:function(m){var p=O(m.length);Ga(m,p);return p}};a=z["_"+a];var h=[],l=0;if(e)for(var n=0;n<e.length;n++){var r=f[c[n]];r?(0===l&&(l=hb()),h[n]=r(e[n])):h[n]=e[n]}c=a.apply(null,h);return c=function(m){0!==l&&ib(l);return"string"===b?Ca(m):"boolean"===b?!!m:m}(c)};z.keepRuntimeAlive=function(){return noExitRuntime};
z.wasmMemory=g;z.ExitStatus=J;z.FS=P;z.PThread=B;var fc;function J(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Sa=function gc(){fc||hc();fc||(Sa=gc)};
function hc(a){function b(){if(!fc&&(fc=!0,z.calledRun=!0,!Aa)){Oa();G||Pa(Ma);ia(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();if(ic){var c=a,e=z._emscripten_proxy_main;c=c||[];var f=c.length+1,h=O(4*(f+1));x()[h>>>2]=Fa(ma);for(var l=1;l<f;l++)x()[(h>>2)+l>>>0]=Fa(c[l-1]);x()[(h>>2)+f>>>0]=0;e(f,h)}if(!G){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;)c=z.postRun.shift(),Na.unshift(c);Pa(Na)}}}a=a||la;if(!(0<Q))if(G)ia(z),Oa(),postMessage({cmd:"loaded"});
else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Qa();Pa(Ka);0<Q||(z.setStatus?(z.setStatus("Running..."),setTimeout(function(){setTimeout(function(){z.setStatus("")},1);b()},1)):b())}}z.run=hc;function lb(a){if(G)throw kb(a),"unwind";if(!noExitRuntime){B.lb();if(z.onExit)z.onExit(a);Aa=!0}na(a,new J(a))}if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();var ic=!0;z.noInitialRun&&(ic=!1);hc();


  return YaneuraOu_K_P.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = YaneuraOu_K_P;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return YaneuraOu_K_P; });
else if (typeof exports === 'object')
  exports["YaneuraOu_K_P"] = YaneuraOu_K_P;
